# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fa2097e53dffe4423efbae29967d8e41682ec476f16497ea65d98537e71da269280c91453ffe8080355a508be0e1b9fc817318736e91565f7b5e2fbe719e81b

test:
  secret_key_base: dbe85aa717b434939651fa44604ddb50bb8c609e2c087d19443263ba36cedf56322cb0fca810963088b4957fb8e8849809d5d778f11313c0d43c5e27e336777f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
